import type { CategoryDefinition, CheckTarget, ServiceDefinition } from './types.ts';

export const CATEGORIES: CategoryDefinition[] = [
  {
    slug: 'gaming',
    name: 'Gaming',
    nameAr: 'الألعاب',
    description: 'Game platforms, stores and multiplayer networks',
    descriptionAr: 'منصات الألعاب والمتاجر وشبكات اللعب الجماعي',
    position: 1,
  },
  {
    slug: 'ai',
    name: 'AI',
    nameAr: 'الذكاء الاصطناعي',
    description: 'Model providers and AI platforms',
    descriptionAr: 'مزوّدو النماذج ومنصات الذكاء الاصطناعي',
    position: 2,
  },
  {
    slug: 'cloud',
    name: 'Cloud',
    nameAr: 'السحابة والبنية التحتية',
    description: 'Cloud, edge, developer platforms and infrastructure',
    descriptionAr: 'الخدمات السحابية ومنصات المطوّرين والبنية التحتية',
    position: 3,
  },
  {
    slug: 'social',
    name: 'Social',
    nameAr: 'التواصل الاجتماعي',
    description: 'Messaging and social networks',
    descriptionAr: 'شبكات التواصل والرسائل',
    position: 4,
  },
  {
    slug: 'media',
    name: 'Media',
    nameAr: 'الوسائط',
    description: 'Media metadata, tracking and streaming services',
    descriptionAr: 'خدمات الوسائط والبيانات الوصفية والمتابعة',
    position: 5,
  },
];

const https = (url: string, label?: string): CheckTarget => ({
  kind: 'https',
  target: url,
  // 401/403/404/412/429 still prove the endpoint answered: they are not connectivity failures.
  expectStatus: [200, 204, 301, 302, 307, 308, 400, 401, 403, 404, 405, 412, 429],
  ...(label ? { label } : {}),
});

const dns = (host: string): CheckTarget => ({ kind: 'dns', target: host });
const tcp = (host: string, port = 443): CheckTarget => ({ kind: 'tcp', target: host, port });

/**
 * The single source of truth for the catalog. Adding a service means adding one entry here
 * (plus a connector implementation if it needs a new source type) — nothing else.
 */
export const SERVICES: ServiceDefinition[] = [
  // ---------------------------------------------------------------- Gaming
  {
    slug: 'steam',
    name: 'Steam',
    category: 'gaming',
    homepage: 'https://store.steampowered.com',
    statusPage: null,
    connector: 'steam-api',
    connectorConfig: { probeUrl: 'https://api.steampowered.com/ISteamWebAPIUtil/GetServerInfo/v1/' },
    sourceKind: 'official-api',
    official: true,
    confidence: 'medium',
    checkTargets: [
      https('https://store.steampowered.com/', 'Store'),
      https('https://api.steampowered.com/ISteamWebAPIUtil/GetServerInfo/v1/', 'Web API'),
      dns('steamcommunity.com'),
      tcp('store.steampowered.com'),
    ],
    limitation: 'Valve publishes no official status or incident feed. The official Web API is used as a liveness signal; the community service steamstat.us blocks automated requests (HTTP 403) and is therefore not used.',
    limitationAr: 'لا تنشر Valve أي تغذية رسمية للحالة أو الأعطال. يُستخدم الـAPI الرسمي كمؤشر على التوفّر، أما خدمة steamstat.us المجتمعية فتحجب الطلبات الآلية (HTTP 403) ولذلك لا تُستخدم.',
  },
  {
    slug: 'playstation-network',
    name: 'PlayStation Network',
    category: 'gaming',
    homepage: 'https://www.playstation.com',
    statusPage: 'https://status.playstation.com/',
    connector: 'connectivity',
    connectorConfig: {},
    sourceKind: 'official-page',
    official: true,
    confidence: 'medium',
    checkTargets: [
      https('https://www.playstation.com/', 'Website'),
      https('https://status.playstation.com/', 'Status page'),
      dns('playstation.com'),
      tcp('www.playstation.com'),
    ],
    limitation: 'Sony runs a status page, but its data feed (status.playstation.com/data/statuses/region/*.json) answered HTTP 404 for every probed region and /api/status answered HTTP 503, so only our own connectivity is reported.',
    limitationAr: 'تملك Sony صفحة حالة، لكن تغذية بياناتها (status.playstation.com/data/statuses/region/*.json) أعادت 404 لكل المناطق التي جُرّبت، وأعاد /api/status الرمز 503، لذلك نعرض فحوص الاتصال الخاصة بنا فقط.',
  },
  {
    slug: 'xbox-network',
    name: 'Xbox Network',
    category: 'gaming',
    homepage: 'https://www.xbox.com',
    statusPage: 'https://support.xbox.com/en-US/xbox-live-status',
    connector: 'xbox-status',
    connectorConfig: { market: 'US', locale: 'en-US', detailedEndpoint: 'https://xnotify.xboxlive.com/servicestatusv4/US/en-US' },
    sourceKind: 'official-api',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://www.xbox.com/', 'Website'),
      https('https://support.xbox.com/en-US/xbox-live-status', 'Status page'),
      dns('xboxlive.com'),
      tcp('www.xbox.com'),
    ],
  },
  {
    slug: 'nintendo-network',
    name: 'Nintendo Network',
    category: 'gaming',
    homepage: 'https://www.nintendo.com',
    statusPage: 'https://www.nintendo.co.jp/netinfo/ja_JP/index.html',
    connector: 'connectivity',
    connectorConfig: {},
    sourceKind: 'official-page',
    official: true,
    confidence: 'medium',
    checkTargets: [
      https('https://www.nintendo.com/', 'Website'),
      https('https://support.nintendo.com/status', 'Support'),
      dns('nintendo.com'),
      tcp('www.nintendo.com'),
    ],
    limitation: 'Nintendo publishes network maintenance information as human-readable pages only (Japanese network-info page); no machine-readable status API was found.',
    limitationAr: 'تنشر Nintendo معلومات صيانة الشبكة كصفحات نصية فقط (صفحة معلومات الشبكة اليابانية)، ولم يتم العثور على واجهة برمجية مقروءة آليًا.',
  },
  {
    slug: 'epic-games',
    name: 'Epic Games',
    category: 'gaming',
    homepage: 'https://www.epicgames.com',
    statusPage: 'https://status.epicgames.com/',
    connector: 'statuspage',
    connectorConfig: { baseUrl: 'https://status.epicgames.com' },
    sourceKind: 'statuspage',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://www.epicgames.com/', 'Website'),
      https('https://store.epicgames.com/', 'Store'),
      dns('epicgames.com'),
      tcp('www.epicgames.com'),
    ],
  },
  {
    slug: 'fortnite',
    name: 'Fortnite',
    category: 'gaming',
    homepage: 'https://www.fortnite.com',
    statusPage: 'https://status.epicgames.com/',
    connector: 'statuspage',
    connectorConfig: { baseUrl: 'https://status.epicgames.com', componentFilter: ['fortnite', 'game services', 'party', 'matchmaking'] },
    sourceKind: 'statuspage',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://www.fortnite.com/', 'Website'),
      dns('fortnite.com'),
      tcp('www.fortnite.com'),
    ],
    limitation: 'Fortnite shares the Epic Games status page; only Fortnite-related components and incidents are surfaced.',
    limitationAr: 'تشترك Fortnite في صفحة حالة Epic Games؛ ويُعرض فقط المكوّنات والحوادث المتعلقة بـFortnite.',
  },
  {
    slug: 'riot-games',
    name: 'Riot Games',
    category: 'gaming',
    homepage: 'https://www.riotgames.com',
    statusPage: 'https://status.riotgames.com/',
    connector: 'connectivity',
    connectorConfig: { keyedApiUrl: 'https://na1.api.riotgames.com/lol/status/v4/platform-data' },
    sourceKind: 'official-page',
    official: true,
    confidence: 'medium',
    checkTargets: [
      https('https://www.riotgames.com/', 'Website'),
      https('https://status.riotgames.com/', 'Status page'),
      dns('riotgames.com'),
      tcp('www.riotgames.com'),
    ],
    limitation: 'The Riot status page is fully client-rendered and exposes no public JSON; the official platform-status API returns HTTP 401 without a Riot API key (set RIOT_API_KEY to enable it).',
    limitationAr: 'صفحة حالة Riot مبنية بالكامل على جافاسكربت ولا تُتيح JSON عامًا، وواجهة حالة المنصّات الرسمية تُعيد الرمز 401 بدون مفتاح Riot API (يمكن تفعيلها بإضافة RIOT_API_KEY).',
  },
  {
    slug: 'ea',
    name: 'EA',
    category: 'gaming',
    homepage: 'https://www.ea.com',
    statusPage: 'https://www.ea.com/service-updates',
    connector: 'connectivity',
    connectorConfig: {},
    sourceKind: 'official-page',
    official: true,
    confidence: 'low',
    checkTargets: [
      https('https://www.ea.com/', 'Website'),
      https('https://www.ea.com/service-updates', 'Service updates'),
      dns('ea.com'),
      tcp('www.ea.com'),
    ],
    limitation: 'EA publishes a service-updates page whose data comes from an undocumented GraphQL endpoint that rejects introspection, so no dependable machine-readable source exists.',
    limitationAr: 'تنشر EA صفحة تحديثات خدمة تعتمد على واجهة GraphQL غير موثّقة ترفض الاستكشاف الداخلي، لذلك لا يوجد مصدر موثوق مقروء آليًا.',
  },
  {
    slug: 'ubisoft',
    name: 'Ubisoft',
    category: 'gaming',
    homepage: 'https://www.ubisoft.com',
    statusPage: 'https://www.ubisoft.com/en-us/help/status',
    connector: 'connectivity',
    connectorConfig: {},
    sourceKind: 'official-page',
    official: true,
    confidence: 'low',
    checkTargets: [
      https('https://www.ubisoft.com/', 'Website'),
      https('https://www.ubisoft.com/en-us/help/status', 'Status page'),
      dns('ubisoft.com'),
      tcp('www.ubisoft.com'),
    ],
    limitation: 'Ubisoft’s status page is a support portal with no public JSON/API; only connectivity can be verified.',
    limitationAr: 'صفحة حالة Ubisoft هي بوابة دعم بدون واجهة JSON/API عامة، لذلك يمكن التحقق من الاتصال فقط.',
  },
  {
    slug: 'battle-net',
    name: 'Battle.net',
    category: 'gaming',
    homepage: 'https://www.blizzard.com',
    statusPage: 'https://account.battle.net/status',
    connector: 'connectivity',
    connectorConfig: {},
    sourceKind: 'official-page',
    official: true,
    confidence: 'low',
    checkTargets: [
      https('https://www.blizzard.com/', 'Website'),
      https('https://account.battle.net/status', 'Status page'),
      dns('battle.net'),
      tcp('account.battle.net'),
    ],
    limitation: 'Blizzard’s status page API answered HTTP 401 (authentication required); no public machine-readable feed is available.',
    limitationAr: 'أعادت واجهة صفحة حالة Blizzard الرمز 401 (تتطلب مصادقة)، ولا توجد تغذية عامة مقروءة آليًا.',
  },
  {
    slug: 'roblox',
    name: 'Roblox',
    category: 'gaming',
    homepage: 'https://www.roblox.com',
    statusPage: 'https://status.roblox.com/',
    connector: 'statusio',
    connectorConfig: { baseUrl: 'https://api.status.io/1.0/status', pageId: '59db90dbcdeb2f04dadcf16d', pageUrl: 'https://status.roblox.com/' },
    sourceKind: 'statusio',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://www.roblox.com/', 'Website'),
      https('https://status.roblox.com/', 'Status page'),
      dns('roblox.com'),
      tcp('www.roblox.com'),
    ],
  },
  {
    slug: 'minecraft',
    name: 'Minecraft',
    category: 'gaming',
    homepage: 'https://www.minecraft.net',
    statusPage: null,
    connector: 'connectivity',
    connectorConfig: {},
    sourceKind: 'none',
    official: false,
    confidence: 'medium',
    checkTargets: [
      https('https://www.minecraft.net/', 'Website'),
      https('https://api.minecraftservices.com/', 'Services API'),
      dns('minecraft.net'),
      tcp('www.minecraft.net'),
    ],
    limitation: 'Mojang retired status.mojang.com (the host no longer resolves) and publishes no replacement feed; the official services API needs authentication.',
    limitationAr: 'أوقفت Mojang خدمة status.mojang.com (النطاق لم يعد موجودًا) دون بديل، وواجهة الخدمات الرسمية تتطلب مصادقة.',
  },
  {
    slug: 'discord',
    name: 'Discord',
    category: 'gaming',
    homepage: 'https://discord.com',
    statusPage: 'https://discordstatus.com/',
    connector: 'statuspage',
    connectorConfig: { baseUrl: 'https://discordstatus.com' },
    sourceKind: 'statuspage',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://discord.com/', 'Website'),
      https('https://discordstatus.com/', 'Status page'),
      dns('discord.com'),
      tcp('discord.com'),
    ],
  },

  // ---------------------------------------------------------------- AI
  {
    slug: 'openai',
    name: 'OpenAI',
    category: 'ai',
    homepage: 'https://openai.com',
    statusPage: 'https://status.openai.com/',
    connector: 'statuspage',
    connectorConfig: { baseUrl: 'https://status.openai.com' },
    sourceKind: 'statuspage',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://openai.com/', 'Website'),
      https('https://api.openai.com/v1/models', 'API'),
      dns('api.openai.com'),
      tcp('api.openai.com'),
    ],
  },
  {
    slug: 'anthropic-claude',
    name: 'Anthropic / Claude',
    category: 'ai',
    homepage: 'https://www.anthropic.com',
    statusPage: 'https://status.claude.com/',
    connector: 'statuspage',
    connectorConfig: { baseUrl: 'https://status.claude.com' },
    sourceKind: 'statuspage',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://www.anthropic.com/', 'Website'),
      https('https://claude.ai/', 'Claude'),
      dns('api.anthropic.com'),
      tcp('api.anthropic.com'),
    ],
  },
  {
    slug: 'google-ai-gemini',
    name: 'Google AI / Gemini',
    category: 'ai',
    homepage: 'https://ai.google.dev',
    statusPage: 'https://status.cloud.google.com/',
    connector: 'google-cloud',
    connectorConfig: {
      incidentsUrl: 'https://status.cloud.google.com/incidents.json',
      pageUrl: 'https://status.cloud.google.com/',
      productFilter: ['vertex', 'gemini', 'generative language', 'ai platform', 'ai studio'],
    },
    sourceKind: 'official-json',
    official: true,
    confidence: 'medium',
    checkTargets: [
      https('https://gemini.google.com/', 'Gemini'),
      https('https://generativelanguage.googleapis.com/', 'Generative Language API'),
      dns('generativelanguage.googleapis.com'),
      tcp('generativelanguage.googleapis.com'),
    ],
    limitation: 'Gemini has no dedicated status page; incidents are derived from Google Cloud’s feed for Vertex AI / Generative Language API products.',
    limitationAr: 'لا تملك Gemini صفحة حالة مستقلة؛ تُستخرج الحوادث من تغذية Google Cloud لمكوّنات Vertex AI وGenerative Language API.',
  },
  {
    slug: 'deepseek',
    name: 'DeepSeek',
    category: 'ai',
    homepage: 'https://www.deepseek.com',
    statusPage: 'https://status.deepseek.com/',
    connector: 'rss-feed',
    connectorConfig: { feedUrl: 'https://status.deepseek.com/feed.rss', pageUrl: 'https://status.deepseek.com/' },
    sourceKind: 'rss',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://www.deepseek.com/', 'Website'),
      https('https://api.deepseek.com/', 'API'),
      dns('api.deepseek.com'),
      tcp('api.deepseek.com'),
    ],
  },
  {
    slug: 'groq',
    name: 'Groq',
    category: 'ai',
    homepage: 'https://groq.com',
    statusPage: 'https://groqstatus.com/',
    connector: 'statuspage',
    connectorConfig: { baseUrl: 'https://groqstatus.com' },
    sourceKind: 'statuspage',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://groq.com/', 'Website'),
      https('https://api.groq.com/openai/v1/models', 'API'),
      dns('api.groq.com'),
      tcp('api.groq.com'),
    ],
  },
  {
    slug: 'hugging-face',
    name: 'Hugging Face',
    category: 'ai',
    homepage: 'https://huggingface.co',
    statusPage: 'https://status.huggingface.co/',
    connector: 'betterstack',
    connectorConfig: { indexUrl: 'https://status.huggingface.co/index.json', pageUrl: 'https://status.huggingface.co/' },
    sourceKind: 'betterstack',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://huggingface.co/', 'Website'),
      https('https://api-inference.huggingface.co/', 'Inference API'),
      dns('huggingface.co'),
      tcp('huggingface.co'),
    ],
  },

  // ---------------------------------------------------------------- Cloud
  {
    slug: 'cloudflare',
    name: 'Cloudflare',
    category: 'cloud',
    homepage: 'https://www.cloudflare.com',
    statusPage: 'https://www.cloudflarestatus.com/',
    connector: 'statuspage',
    connectorConfig: { baseUrl: 'https://www.cloudflarestatus.com' },
    sourceKind: 'statuspage',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://www.cloudflare.com/', 'Website'),
      https('https://1.1.1.1/', '1.1.1.1 DNS'),
      dns('cloudflare.com'),
      tcp('www.cloudflare.com'),
    ],
  },
  {
    slug: 'github',
    name: 'GitHub',
    category: 'cloud',
    homepage: 'https://github.com',
    statusPage: 'https://www.githubstatus.com/',
    connector: 'statuspage',
    connectorConfig: { baseUrl: 'https://www.githubstatus.com' },
    sourceKind: 'statuspage',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://github.com/', 'Website'),
      https('https://api.github.com/', 'API'),
      dns('github.com'),
      tcp('github.com'),
    ],
  },
  {
    slug: 'aws',
    name: 'AWS',
    category: 'cloud',
    homepage: 'https://aws.amazon.com',
    statusPage: 'https://health.aws.amazon.com/health/status',
    connector: 'aws-health',
    connectorConfig: {
      eventsUrl: 'https://health.aws.amazon.com/public/currentevents',
      rssUrl: 'https://status.aws.amazon.com/rss/all.rss',
      pageUrl: 'https://health.aws.amazon.com/health/status',
    },
    sourceKind: 'official-json',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://aws.amazon.com/', 'Website'),
      https('https://status.aws.amazon.com/', 'Status page'),
      dns('aws.amazon.com'),
      tcp('aws.amazon.com'),
    ],
  },
  {
    slug: 'microsoft-azure',
    name: 'Microsoft Azure',
    category: 'cloud',
    homepage: 'https://azure.microsoft.com',
    statusPage: 'https://azure.status.microsoft/en-us/status/',
    connector: 'rss-feed',
    connectorConfig: { feedUrl: 'https://azure.status.microsoft/en-us/status/feed/', pageUrl: 'https://azure.status.microsoft/en-us/status/', emptyMeansOperational: true },
    sourceKind: 'rss',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://azure.microsoft.com/', 'Website'),
      https('https://portal.azure.com/', 'Portal'),
      dns('azure.microsoft.com'),
      tcp('portal.azure.com'),
    ],
  },
  {
    slug: 'google-cloud',
    name: 'Google Cloud',
    category: 'cloud',
    homepage: 'https://cloud.google.com',
    statusPage: 'https://status.cloud.google.com/',
    connector: 'google-cloud',
    connectorConfig: { incidentsUrl: 'https://status.cloud.google.com/incidents.json', pageUrl: 'https://status.cloud.google.com/' },
    sourceKind: 'official-json',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://cloud.google.com/', 'Website'),
      https('https://console.cloud.google.com/', 'Console'),
      dns('cloud.google.com'),
      tcp('console.cloud.google.com'),
    ],
  },
  {
    slug: 'vercel',
    name: 'Vercel',
    category: 'cloud',
    homepage: 'https://vercel.com',
    statusPage: 'https://www.vercel-status.com/',
    connector: 'statuspage',
    connectorConfig: { baseUrl: 'https://www.vercel-status.com' },
    sourceKind: 'statuspage',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://vercel.com/', 'Website'),
      https('https://api.vercel.com/', 'API'),
      dns('vercel.com'),
      tcp('vercel.com'),
    ],
  },
  {
    slug: 'digitalocean',
    name: 'DigitalOcean',
    category: 'cloud',
    homepage: 'https://www.digitalocean.com',
    statusPage: 'https://status.digitalocean.com/',
    connector: 'statuspage',
    connectorConfig: { baseUrl: 'https://status.digitalocean.com' },
    sourceKind: 'statuspage',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://www.digitalocean.com/', 'Website'),
      https('https://api.digitalocean.com/', 'API'),
      dns('digitalocean.com'),
      tcp('api.digitalocean.com'),
    ],
  },

  // ---------------------------------------------------------------- Social
  {
    slug: 'whatsapp',
    name: 'WhatsApp',
    category: 'social',
    homepage: 'https://www.whatsapp.com',
    statusPage: 'https://metastatus.com/',
    connector: 'connectivity',
    connectorConfig: {},
    sourceKind: 'official-page',
    official: true,
    confidence: 'low',
    checkTargets: [
      https('https://www.whatsapp.com/', 'Website'),
      https('https://web.whatsapp.com/', 'Web'),
      dns('whatsapp.com'),
      tcp('web.whatsapp.com'),
    ],
    limitation: 'Meta’s status page (metastatus.com) is client-rendered and exposes no public JSON; its metrics endpoints use parameters that are not discoverable, so only connectivity is reported.',
    limitationAr: 'صفحة حالة Meta (metastatus.com) مبنية على جافاسكربت ولا تُتيح JSON عامًا، ونقاط القياس فيها تستخدم معاملات غير معروفة، لذلك نعرض فحوص الاتصال فقط.',
  },
  {
    slug: 'instagram',
    name: 'Instagram',
    category: 'social',
    homepage: 'https://www.instagram.com',
    statusPage: 'https://metastatus.com/',
    connector: 'connectivity',
    connectorConfig: {},
    sourceKind: 'official-page',
    official: true,
    confidence: 'low',
    checkTargets: [
      https('https://www.instagram.com/', 'Website'),
      dns('instagram.com'),
      tcp('www.instagram.com'),
    ],
    limitation: 'Same limitation as WhatsApp: Meta publishes no machine-readable status feed.',
    limitationAr: 'نفس قيد واتساب: لا تنشر Meta تغذية حالة مقروءة آليًا.',
  },
  {
    slug: 'facebook',
    name: 'Facebook',
    category: 'social',
    homepage: 'https://www.facebook.com',
    statusPage: 'https://metastatus.com/',
    connector: 'connectivity',
    connectorConfig: {},
    sourceKind: 'official-page',
    official: true,
    confidence: 'low',
    checkTargets: [
      https('https://www.facebook.com/', 'Website'),
      dns('facebook.com'),
      tcp('www.facebook.com'),
    ],
    limitation: 'Same limitation as WhatsApp: Meta publishes no machine-readable status feed.',
    limitationAr: 'نفس قيد واتساب: لا تنشر Meta تغذية حالة مقروءة آليًا.',
  },
  {
    slug: 'x',
    name: 'X',
    category: 'social',
    homepage: 'https://x.com',
    statusPage: null,
    connector: 'connectivity',
    connectorConfig: {},
    sourceKind: 'none',
    official: false,
    confidence: 'medium',
    checkTargets: [
      https('https://x.com/', 'Website'),
      https('https://api.x.com/', 'API host'),
      dns('x.com'),
      tcp('api.x.com'),
    ],
    limitation: 'X has no official status page: status.twitter.com and status.x.com do not resolve, and the community page api.twitterstat.us reports the page as inactive (HTTP 401).',
    limitationAr: 'لا تملك X صفحة حالة رسمية: النطاقان status.twitter.com وstatus.x.com غير موجودين، والصفحة المجتمعية api.twitterstat.us معلنة كغير نشطة (HTTP 401).',
  },
  {
    slug: 'tiktok',
    name: 'TikTok',
    category: 'social',
    homepage: 'https://www.tiktok.com',
    statusPage: null,
    connector: 'connectivity',
    connectorConfig: {},
    sourceKind: 'none',
    official: false,
    confidence: 'medium',
    checkTargets: [
      https('https://www.tiktok.com/', 'Website'),
      dns('tiktok.com'),
      tcp('www.tiktok.com'),
    ],
    limitation: 'No official TikTok status surface was found (status.tiktok.com does not resolve, developers.tiktok.com/status returns HTTP 404).',
    limitationAr: 'لم يتم العثور على واجهة حالة رسمية لـTikTok (النطاق status.tiktok.com غير موجود، وdevelopers.tiktok.com/status يُعيد 404).',
  },
  {
    slug: 'reddit',
    name: 'Reddit',
    category: 'social',
    homepage: 'https://www.reddit.com',
    statusPage: 'https://www.redditstatus.com/',
    connector: 'statuspage',
    connectorConfig: { baseUrl: 'https://www.redditstatus.com' },
    sourceKind: 'statuspage',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://www.reddit.com/', 'Website'),
      https('https://oauth.reddit.com/', 'API host'),
      dns('reddit.com'),
      tcp('www.reddit.com'),
    ],
  },
  {
    slug: 'telegram',
    name: 'Telegram',
    category: 'social',
    homepage: 'https://telegram.org',
    statusPage: null,
    connector: 'connectivity',
    connectorConfig: {},
    sourceKind: 'none',
    official: false,
    confidence: 'medium',
    checkTargets: [
      https('https://telegram.org/', 'Website'),
      https('https://core.telegram.org/', 'Core'),
      dns('telegram.org'),
      tcp('telegram.org'),
    ],
    limitation: 'Telegram publishes no status page (status.telegram.org is not a status surface); incident news is posted on Telegram channels only.',
    limitationAr: 'لا تنشر Telegram صفحة حالة (status.telegram.org ليست واجهة حالة)، وتُنشر أخبار الأعطال على قنوات تلجرام فقط.',
  },

  // ---------------------------------------------------------------- Media
  {
    slug: 'nuvio',
    name: 'Nuvio',
    category: 'media',
    homepage: 'https://nuvio.tv',
    statusPage: 'https://status.nuvio.tv/',
    connector: 'nuvio-status',
    connectorConfig: { statusUrl: 'https://status.nuvio.tv/api/status', pageUrl: 'https://status.nuvio.tv/' },
    sourceKind: 'official-json',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://nuvio.tv/', 'Website'),
      https('https://api.nuvio.tv/', 'API'),
      dns('api.nuvio.tv'),
      tcp('api.nuvio.tv'),
    ],
  },
  {
    slug: 'stremio',
    name: 'Stremio',
    category: 'media',
    homepage: 'https://www.stremio.com',
    statusPage: null,
    connector: 'connectivity',
    connectorConfig: {},
    sourceKind: 'none',
    official: false,
    confidence: 'medium',
    checkTargets: [
      https('https://www.stremio.com/', 'Website'),
      https('https://api.strem.io/api/', 'API'),
      dns('strem.io'),
      tcp('api.strem.io'),
    ],
    limitation: 'Stremio publishes no status page (status.stremio.com does not resolve); only connectivity is measured.',
    limitationAr: 'لا تنشر Stremio صفحة حالة (النطاق status.stremio.com غير موجود)، ويُقاس الاتصال فقط.',
  },
  {
    slug: 'tmdb',
    name: 'TMDB',
    category: 'media',
    homepage: 'https://www.themoviedb.org',
    statusPage: 'https://status.themoviedb.org/',
    connector: 'rss-feed',
    connectorConfig: { feedUrl: 'https://status.themoviedb.org/rss', pageUrl: 'https://status.themoviedb.org/' },
    sourceKind: 'rss',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://www.themoviedb.org/', 'Website'),
      https('https://api.themoviedb.org/3/', 'API'),
      dns('api.themoviedb.org'),
      tcp('api.themoviedb.org'),
    ],
  },
  {
    slug: 'trakt',
    name: 'Trakt',
    category: 'media',
    homepage: 'https://trakt.tv',
    statusPage: 'https://status.trakt.tv/',
    connector: 'uptime-json',
    connectorConfig: {
      monitorsUrl: 'https://status.trakt.tv/api/getMonitorList/wVLWNFLGN9',
      eventsUrl: 'https://status.trakt.tv/api/getEventFeed/wVLWNFLGN9',
      pageUrl: 'https://status.trakt.tv/',
    },
    sourceKind: 'official-json',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://trakt.tv/', 'Website'),
      https('https://api.trakt.tv/', 'API'),
      dns('api.trakt.tv'),
      tcp('api.trakt.tv'),
    ],
  },
  {
    slug: 'simkl',
    name: 'Simkl',
    category: 'media',
    homepage: 'https://simkl.com',
    statusPage: 'https://status.simkl.com/',
    connector: 'uptime-json',
    connectorConfig: {
      monitorsUrl: 'https://status.simkl.com/api/getMonitorList/Nx8xTN71j',
      eventsUrl: 'https://status.simkl.com/api/getEventFeed/Nx8xTN71j',
      pageUrl: 'https://status.simkl.com/',
    },
    sourceKind: 'official-json',
    official: true,
    confidence: 'high',
    checkTargets: [
      https('https://simkl.com/', 'Website'),
      https('https://api.simkl.com/', 'API'),
      dns('api.simkl.com'),
      tcp('api.simkl.com'),
    ],
  },
];

export const SERVICE_BY_SLUG: Map<string, ServiceDefinition> = new Map(SERVICES.map((service) => [service.slug, service]));

export function servicesByCategory(category: string): ServiceDefinition[] {
  return SERVICES.filter((service) => service.category === category);
}

export function findService(slug: string): ServiceDefinition | undefined {
  return SERVICE_BY_SLUG.get(slug);
}

export function assertCatalogIntegrity(): string[] {
  const problems: string[] = [];
  const seen = new Set<string>();
  for (const service of SERVICES) {
    if (seen.has(service.slug)) problems.push(`duplicate slug: ${service.slug}`);
    seen.add(service.slug);
    if (!CATEGORIES.some((category) => category.slug === service.category)) {
      problems.push(`${service.slug}: unknown category ${service.category}`);
    }
    if (service.checkTargets.length === 0) problems.push(`${service.slug}: no check targets`);
  }
  return problems;
}
